apiVersion: v1
kind: Pod
metadata:
  name: dind
  namespace: pyats
spec:
  containers:
    - name: dind-ubuntu
      image: fsedano/dind-ubuntu:1
      env:
      - name: DOCKER_HOST
        value: tcp://localhost:2375
      volumeMounts:
        - name: registrypassword
          mountPath: /root/registrypassword
          readOnly: true
        - name: gitkeys
          mountPath: /root/gitkeys
          readOnly: true
      command: ["/bin/bash", "-c", "sleep 99999"]
    - name: dind
      image: docker:18.05-dind
      securityContext:
        privileged: true
      volumeMounts:
        - name: dind-storage
          mountPath: /var/lib/docker
  volumes:
    - name: dind-storage
      emptyDir: {}
    - name: registrypassword
      secret:
        secretName: registrypassword
        defaultMode: 0400
    - name: gitkeys
      secret:
        secretName: gitkeys
        defaultMode: 0400